/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED BY `npx convex dev`; this copy matches
 * the standard template so the repository type-checks before a deployment exists.
 */
import type * as auth_alfiz from "../auth/alfiz.js";
import type * as auth_tenancy from "../auth/tenancy.js";
import type * as connections_store from "../connections/store.js";
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  "auth/alfiz": typeof auth_alfiz;
  "auth/tenancy": typeof auth_tenancy;
  "connections/store": typeof connections_store;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
