/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED BY `npx convex dev`; this copy matches
 * the standard template so the repository type-checks before a deployment exists.
 */
import type * as alfiz from "../alfiz.js";
import type * as tenancy from "../tenancy.js";
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  alfiz: typeof alfiz;
  tenancy: typeof tenancy;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
